// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_UzHec4h9urDK7cCjVqBsTI4ONZfckw0',
    appId: '1:32540171705:web:4e2d0009674287483caa68',
    messagingSenderId: '32540171705',
    projectId: 'report-rover-fe0b1',
    authDomain: 'report-rover-fe0b1.firebaseapp.com',
    storageBucket: 'report-rover-fe0b1.appspot.com',
    measurementId: 'G-3HZ7MY3614',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQMd5FMCMt1D94_G1ILj7a0eDYb-6dgGU',
    appId: '1:32540171705:android:2310bf0b7041ddc73caa68',
    messagingSenderId: '32540171705',
    projectId: 'report-rover-fe0b1',
    storageBucket: 'report-rover-fe0b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHrY9VZEEdxEMhrlUZAxAhIaKHO_oR1w0',
    appId: '1:32540171705:ios:62fdd2706cf3771b3caa68',
    messagingSenderId: '32540171705',
    projectId: 'report-rover-fe0b1',
    storageBucket: 'report-rover-fe0b1.appspot.com',
    iosBundleId: 'com.example.report',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHrY9VZEEdxEMhrlUZAxAhIaKHO_oR1w0',
    appId: '1:32540171705:ios:62fdd2706cf3771b3caa68',
    messagingSenderId: '32540171705',
    projectId: 'report-rover-fe0b1',
    storageBucket: 'report-rover-fe0b1.appspot.com',
    iosBundleId: 'com.example.report',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_UzHec4h9urDK7cCjVqBsTI4ONZfckw0',
    appId: '1:32540171705:web:8a5525a33aa1e1053caa68',
    messagingSenderId: '32540171705',
    projectId: 'report-rover-fe0b1',
    authDomain: 'report-rover-fe0b1.firebaseapp.com',
    storageBucket: 'report-rover-fe0b1.appspot.com',
    measurementId: 'G-V7W211PYGF',
  );

}